language: php
php:
    - '5.4' # Only some of the tests will run for this version, as we only support PHP >= 7.0
    - '7.0'
    - '7.1'
dist: trusty
sudo: required # this seems to be required for some reason to get MySQL to work
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb'
  - mysql -e "GRANT ALL ON testdb.* TO 'travis'@'localhost'"
script:
  - ./test/test_for_syntax_errors.sh
  - ./test/test_installation.sh
  - curl -sOL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && php phpcs.phar && rm phpcs.phar
